data <- read.table("household_power_consumption.txt", header =TRUE, sep=";")
subData <- subset(data, Date %in% c("1/2/2007","2/2/2007"))
globalActivePower<-as.numeric(subData$Global_active_power)
png("plot2.png", width=480, height=480)
time <- strptime(paste(subData$Date, subData$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot(time, globalActivePower,ylab = "Global Active Power (kilowatts)",type = "l")
dev.off()