data <- read.table("household_power_consumption.txt", header =TRUE, sep=";")
subData <- subset(data, Date %in% c("1/2/2007","2/2/2007"))
time <- strptime(paste(subData$Date, subData$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
globalActivePower<-as.numeric(subData$Global_active_power)
globalReactivePower<-as.numeric(subData$Global_reactive_power)
voltage <- as.numeric(subData$Voltage)
subMetering1 <- as.numeric(subData$Sub_metering_1)
subMetering2 <- as.numeric(subData$Sub_metering_2)
subMetering3 <- as.numeric(subData$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(time, globalActivePower, type="l",ylab="Global Active Power")
plot(time, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(time, subMetering1, type="l", ylab="Energy Submetering")
lines(time, subMetering2, type="l", col="red")
lines(time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(time, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()